spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

zuul:
  ignored-patterns: /login
  routes:
    security-service:
      sensitive-headers: Cookie,Set-Cookie,Authorization
      path: /**
      url: http://localhost:8084/

